monolith/views/auth.py
from flask import Blueprint, redirect, render_template
from flask_login import login_user, logout_user

from monolith.database import User, db
from monolith.forms import LoginForm

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    """Login with a user

    :returns: the rendered template of the page
    :rtype: text
    """
    form = LoginForm()
    if form.validate_on_submit():
        # check the fields and login if successful
        email, password = form.data["email"], form.data["password"]
        q = db.session.query(User).filter(User.email == email)
        user = q.first()
        if user is not None:
            if user.authenticate(password):
                if user.is_active:
                    login_user(user)
                    return redirect("/")
                else:
                    # if the user is not active, check if it has been banned or the account is deleted
                    errorstring = ""
                    if user.reports >= 3:
                        errorstring = (
                            "You have been banned and you account has been deleted."
                        )
                    else:
                        errorstring = "You unregistered from the service."
                    return render_template(
                        "login.html",
                        form=form,
                        error=errorstring
                        + " All your messages will be delivered anyway.",
                    )
            else:
                form.password.errors.append("Invalid password")
        else:
            form.email.errors.append("Unknown email address")

    return render_template("login.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect("/")

monolith/views/home.py
from flask import Blueprint, render_template

from monolith.auth import current_user
from monolith.forms import MessageForm

home = Blueprint("home", __name__)


@home.route("/")
def index():
    form = None

    if current_user is not None and hasattr(current_user, "id"):
        form = MessageForm()

    return render_template("index.html", form=form)


@home.route("/error_page")
def to_error_page(msg):  # pragma: no cover
    return render_template(
        "error_page.html", message="Ooops, something went wrong! ({0})".format(msg)
    )


@home.route("/settings")
def settings():  # pragma: no cover
    return render_template("settings.html")

monolith/views/users.py
import datetime
from flask import (
    Blueprint,
    json,
    redirect,
    render_template,
    request,
    jsonify,
    make_response,
    abort,
)
from flask_login import logout_user

from monolith.database import User, db
from monolith.forms import BlackListForm, UserForm, ChangePassForm
from monolith.auth import check_authenticated, current_user
import monolith.user_query

users = Blueprint("users", __name__)


@users.route("/users")
def _users():  # pragma: no cover
    _users = db.session.query(User)
    return render_template("users.html", users=_users)


@users.route("/content_filter")
def content_filter():  # pragma: no cover
    return render_template("content_filter.html", feedback="")


@users.route("/search_user")
def _search_user():  # pragma: no cover
    return render_template("search_user.html")


@users.route("/user/account", methods=["GET"])
def _user():  # pragma: no cover
    check_authenticated()
    data = current_user.dateofbirth
    date_of_birth = data.strftime("%a, %d %B, %Y")
    return render_template("account_data.html", user=current_user, date=date_of_birth)


@users.route("/create_user", methods=["POST", "GET"])
def create_user():
    """Create a user

    :returns: the rendered template of the page
    :rtype: text
    """
    form = UserForm()

    if request.method == "POST":
        if form.validate_on_submit():
            # check if date of birth is valid (in the past)
            inputdate = form.dateofbirth.data
            if inputdate is None or inputdate > datetime.date.today():
                return render_template(
                    "create_user.html",
                    form=form,
                    error="Date of birth cannot be empty or in the future",
                )

            # check if a user with the same email already exists
            email = form.email.data
            if monolith.user_query.get_user_by_email(email) is not None:
                return render_template(
                    "create_user.html",
                    form=form,
                    error="A user with that email already exists",
                )

            # create the user
            new_user = User()
            form.populate_obj(new_user)
            """
            Password should be hashed with some salt. For example if you choose a hash function x, 
            where x is in [md5, sha1, bcrypt], the hashed_password should be = x(password + s) where
            s is a secret key.
            """
            new_user.set_password(form.password.data)
            db.session.add(new_user)
            db.session.commit()
            return redirect("/login")
    elif request.method == "GET":  # pragma: no cover
        return render_template("create_user.html", form=form, error="")


@users.route("/api/user/recipients", methods=["GET"])
def get_recipients():
    """Get all the possible message recipients for the current user

    :returns: the json of all the possible recipients
    :rtype: json
    """
    result = monolith.user_query.get_recipients(getattr(current_user, "id"))
    l = [{"id": i.id, "email": i.email} for i in result]
    return jsonify(l)


@users.route("/user/unregister")
def unregister():
    """Unregister the current user from the service

    :returns: redirect to landing page
    :rtype: response
    """
    check_authenticated()
    userid = getattr(current_user, "id")
    logout_user()
    user = User.query.filter(User.id == userid).first()
    user.is_active = False
    db.session.commit()
    return redirect("/")


@users.route("/user/data", methods=["POST", "GET"])
def change_data_user():
    """Update the data of the current user

    :returns: the rendered template of the page
    :rtype: text
    """
    check_authenticated()
    form = UserForm()

    if request.method == "POST":
        # check if inputs are valid
        check_mail_db = (
            db.session.query(User)
            .filter(User.email == request.form["textemail"])
            .first()
        )
        if (
            request.form["textfirstname"] == ""
            or request.form["textlastname"] == ""
            or request.form["textemail"] == ""
            or request.form["textbirth"] == ""
            or (
                check_mail_db is not None
                and check_mail_db.id != getattr(current_user, "id")
            )
        ):
            return render_template(
                "edit_profile.html",
                form=form,
                user=current_user,
                error="All fields must be completed or the email is already associated to an account",
            )

        # update the user data
        userid = getattr(current_user, "id")
        user = User.query.filter(User.id == userid).first()
        user.firstname = request.form["textfirstname"]
        user.lastname = request.form["textlastname"]
        user.email = request.form["textemail"]
        data = request.form["textbirth"]
        date_as_datetime = datetime.datetime.strptime(data, "%Y-%m-%d")
        user.dateofbirth = date_as_datetime

        db.session.commit()
        return redirect("/user/account")
    elif request.method == "GET":  # pragma: no cover
        return render_template("edit_profile.html", form=form, user=current_user)


@users.route("/user/password", methods=["POST", "GET"])
def change_pass_user():
    """Change the password of the current user

    :returns: the rendered template of the page
    :rtype: text
    """
    check_authenticated()
    form = ChangePassForm()
    stringError = ""

    if request.method == "POST":
        userid = getattr(current_user, "id")
        user = User.query.filter(User.id == userid).first()
        current_password = form.currentpassword.data
        new_pass = form.newpassword.data
        confirmpass = form.confirmpassword.data

        # check that current and confirmation password are correct
        if user.authenticate(current_password):
            if new_pass == confirmpass:
                user.set_password(new_pass)
            else:
                stringError = "Check the correctness of the confirmation password!"
                return render_template(
                    "reset_password.html", form=form, error=stringError
                )
        else:
            stringError = "Wrong current password!"
            return render_template("reset_password.html", form=form, error=stringError)

        db.session.commit()
        return render_template(
            "reset_password.html", form=form, success="Password updated!"
        )
    elif request.method == "GET":  # pragma: no cover
        return render_template("reset_password.html", form=form)


@users.route("/user/report", methods=["GET", "POST"])
def report():
    """Report a user

    :returns: the rendered template of the page
    :rtype: text
    """
    check_authenticated()
    if request.method == "GET":  # pragma: no cover
        return render_template("report_user.html")
    else:
        # get the mail of the user to be reported and report it
        mail = str(request.form["useremail"])
        if mail is not None and not mail.isspace():
            user = User.query.filter(User.email == mail).first()
            if user is None:
                return render_template(
                    "report_user.html",
                    error=mail + " does not exist.",
                    reported="",
                )
            user.reports += 1
            banned = ""
            # if the user has 3 or more reports ban the account deactivating it
            if user.reports >= 3:
                user.is_active = False
                banned = " and banned"
            db.session.commit()
            return render_template(
                "report_user.html",
                error="",
                reported=mail + " has been reported" + banned + ".",
            )
        else:  # pragma: no cover
            return render_template(
                "report_user.html",
                error="You have to specify an email to report a user.",
                reported="",
            )


@users.route("/user/black_list", methods=["GET", "POST"])
def handle_black_list():
    """Get all the users blacklisted by the current user or add/remove users to the blacklist

    :returns: the response from the server or the rendered template
    :rtype: text
    """
    check_authenticated()
    owner_id = getattr(current_user, "id")
    if request.method == "POST":
        # remove or add users to the blacklist
        result = False
        json_data = json.loads(request.data)
        members_id = json_data["users"]
        if json_data["op"] == "delete":
            result = monolith.user_query.remove_from_blacklist(owner_id, members_id)
        elif json_data["op"] == "add":
            result = monolith.user_query.add_to_blacklist(owner_id, members_id)

        return _prepare_json_response(owner_id, 200 if result else 500)
    elif request.method == "GET":  # pragma: no cover
        # get all the blacklisted users
        f = BlackListForm()
        result = monolith.user_query.get_blacklist(owner_id)
        black_list = [usr[1] for usr in result]
        f.users.choices = monolith.user_query.get_blacklist_candidates(owner_id)
        f.black_users.choices = result
        return render_template(
            "black_list.html", form=f, black_list=black_list, size=len(black_list)
        )


def _prepare_json_response(owner_id, status):
    """Create and make the json response from server

    :param owner_id: the id of the user to retrieve the data of
    :type owner_id: int
    :param status: the status code to be returned
    :type status: int
    :returns: the response from the server
    :rtype: Response
    """
    body = dict()
    choices = monolith.user_query.get_blacklist_candidates(owner_id)
    body.update({"users": [{"id": i[0], "email": i[1]} for i in choices]})
    black_list = monolith.user_query.get_blacklist(owner_id)

monolith/templates/account_data.html
{% extends "base.html" %}
{% block title %}Account data{% endblock %}

{% block content %}
<h1>Account data</h1>
<a href="/" class="btn btn-outline-primary">Homepage</a>
<a href="{{url_for('home.settings')}}" class="btn btn-outline-primary">Back to settings</a><br>

<div>
	<br>
	<h1>{{user.firstname}} {{user.lastname}}</h1>
	<dl>
		<dd>User mail: <b>{{ user.email }}</b></dd>
		<dd>Date of birth: <b>{{ date }}</b></dd>
	</dl>
	<a href="{{url_for('users.change_data_user')}}" class="btn btn-success" tabindex="-1" role="button"
		aria-disabled="true">Edit profile</a>
	<a href="{{url_for('users.change_pass_user')}}" class="btn btn-warning" tabindex="-1" role="button"
		aria-disabled="true">Change
		password</a>
</div><br>
{% endblock %}

monolith/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %} | MMIAB</title>

	<script src="{{url_for('static', filename='jquery.min.js')}}"></script>
	<link href="{{url_for('static', filename='bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
	<script src="{{url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js')}}"></script>
	<style>
		body {
			margin: 2rem 2rem 2rem 2rem
		}
	</style>
	{% block html_head %}{% endblock %}
</head>

<body>
	{% block content %}{% endblock %}
	{% block scripts %}{% endblock %}
</body>

</html>

monolith/templates/black_list.html
{% extends "base.html" %}
{% block title %}Blacklist{% endblock %}

{% block scripts %}
<script type="application/javascript">
	function get_users_id(form, operation) {
		let name = operation === "add" ? "users" : "black_users";
		let arr = $(form).serializeArray();
		console.log(arr);
		let ids = [];
		arr.forEach(item => { if (item["name"] === name) ids.push(item["value"]); })
		return ids;
	}
	function update_black_list(form, operation) {
		let body = JSON.stringify({ op: operation, users: get_users_id(form, operation) });
		$.ajax({
			type: "POST",
			contentType: "application/json",
			dataType: "json",
			data: body,
			url: "{{url_for('users.handle_black_list')}}",
			success: function (data, status) {
				console.log("Response: ");
				console.log(data);
				$('#black_users').empty();
				data["black_users"].forEach(item => {
					$('#black_users').append($('<option>', {
						value: item.id,
						text: item.email
					}));
				});
				$("#users").empty();
				data["users"].forEach(item => {
					$('#users').append($('<option>', {
						value: item.id,
						text: item.email
					}));
				});
				alert("Black list updated successfully!")
			},
			error: function (a, b, c) {
				console.log(a + " " + b + " " + c);
				alert("Ooops, something went wrong!")
			},
			cache: false
		});
	}
</script>
{% endblock %}

{% block content %}
<h1>Blacklist</h1>
<a href="/" class="btn btn-outline-primary">Homepage</a>
<a href="{{url_for('home.settings')}}" class="btn btn-outline-primary">Back to settings</a><br><br>
<form>
	{{ form.hidden_tag() }}
	<label for="users">Users non-present in your black list</label>
	<br>
	<select multiple name="users" required id="users">
		{% for i in form.users %}
		{{i}}
		{%endfor%}
	</select>
	<br>
	<br>
	<button type="button" class="btn btn-primary" onclick="javascript:update_black_list(document.forms[0],'add')"> Add
		users</button>
</form><br>

<form>
	{{ form.hidden_tag() }}
	<label for="users">Users present in your black list</label>
	<br>
	<select multiple name="black_users" required id="black_users">
		{% for i in form.black_users %}
		{{i}}
		{%endfor%}
	</select>
	<br>
	<br>
	<button type="button" class="btn btn-danger" onclick="javascript :
        update_black_list(document.forms[1],'delete')">Delete users</button>
</form>
<br>
<p>(<i>Hint: use Ctrl or Cmd to select multiple users</i>)</p>
{% endblock %}

monolith/templates/calendar.html
{% extends "base.html" %}
{% block title %}Calendar{% endblock %}

{% block html_head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />

<link href="{{url_for('static', filename='style.css')}}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Calendar</h1>
<a href="/" class="btn btn-outline-primary">Homepage</a><br><br>
<h2>Select a date and see the outgoing messages for that day</h2>
<div class="container-calendar">
	<div class="calendar">
		<div class="month">
			<i class="fas fa-angle-left prev"></i>
			<div class="date">
				<h1></h1>
				<p></p>
			</div>
			<i class="fas fa-angle-right next"></i>
		</div>
		<div class="weekdays">
			<div>Sun</div>
			<div>Mon</div>
			<div>Tue</div>
			<div>Wed</div>
			<div>Thu</div>
			<div>Fri</div>
			<div>Sat</div>
		</div>
		<div class="days"></div>
	</div>
	<div class="message" id="sentmsg"></div>
</div>

<div id="modal_read" class="modal">
	<div class="modal-content">
		<span class="close">&times;</span>
		<div id="modal_read_text">
			<p>ASE &lt;3 </p>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='calendar.js') }}"></script>
{% endblock %}

monolith/templates/content_filter.html
{% extends "base.html" %}
{% block title %}Content filter{% endblock %}

{% block content %}
<h1>Content filter</h1>

<a href="/" class="btn btn-outline-primary">Homepage</a>
<a href="{{url_for('home.settings')}}" class="btn btn-outline-primary">Back to settings</a><br><br>

Press enable to activate a content filter that automatically censors bad words!<br><br>

<form method="POST">
	<input type="radio" id="enable_choice" name="filter" value="1">
	<label for="enable_choice">Enable</label>
	<input type="radio" id="disable_choice" name="filter" value="0">
	<label for="disable_choice">Disable</label><br>
	<button type="submit" formaction="{{url_for('users.set_content_filter')}}" class="btn btn-primary">Save</button><br><br>
</form>

{{feedback}}
{% endblock %}

monolith/templates/create_user.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block content %}
<h1>Create a new user</h1>
<a href="/" class="btn btn-outline-primary">Homepage</a><br><br>
<p style="color:red">{{error}}</p>
<form action="" method="POST">
	{{ form.hidden_tag() }}
	<dl>
		{% for field in form.display %}
		<dt>{{ form[field].label }}</dt>
		<dd>{{ form[field]() }}</dd><br>
		{% if form[field].errors %}
		{% for e in form[field].errors %}
		<p class="help-block">{{ e }}</p>
		{% endfor %}
		{% endif %}
		{% endfor %}
	</dl>
	<p><input type=submit value="Submit"></p>
</form>
{% endblock %}

monolith/templates/edit_profile.html
{% extends "base.html" %}
{% block title %}Edit profile{% endblock %}

{% block content %}
<h1>Edit profile</h1>
<a href="/" class="btn btn-outline-primary">Homepage</a>
<a href="{{url_for('home.settings')}}" class="btn btn-outline-primary">Back to settings</a><br><br>

<div>
	<form action="" method="POST">
		{{ form.hidden_tag() }}
		<h5>First name</h5><input type="text" name="textfirstname" value={{user.firstname}}>
		<h5>Last name</h5><input type="text" name="textlastname" value={{user.lastname}}>
		<h5>Email</h5><input type="text" name="textemail" value={{user.email}}>
		<h5>Date of birth</h5><input type="date" name="textbirth" value={{user.dateofbirth}}>
		<p>
			<br>
			<input type=submit value="Submit" class="btn btn-outline-primary"><br>
			<h7 style="color: red;"> {{ error }}</h7>
</div>
{% endblock %}

monolith/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block content %}
<h1>My Message in a Bottle</h1>
{% if current_user.is_authenticated %}
<br>Hi!<br>
You're now logged in as <b>{{ current_user.firstname }} {{current_user.lastname }}</b> ({{current_user.email}})<br><br>
<a href="{{url_for('users._search_user')}}">Search a user</a><br>
<a href="{{url_for('message.mailbox')}}">Mailbox</a><br>
<a href="{{url_for('message._send_message')}}">Send or draft a message</a><br>
<a href="{{url_for('message.calendar')}}">Calendar of outgoing messages</a>
<hr>
<a href="{{url_for('home.settings')}}">Settings</a><br>
<a href="{{url_for('auth.logout')}}">Logout</a>
<h2>{{welcome}}</h2>
<h1>{{message}}</h1>
{% else %}
Hi, please <a href="{{url_for('auth.login')}}">Log in</a> or <a href="{{url_for('users.create_user')}}">Register</a>
{% endif %}
{% endblock %}

monolith/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<form action="" method="POST">
	<h1>Please sign in</h1>
	{{ form.hidden_tag() }}
	<dl>
		{% for field in form.display %}
		<dt>{{ form[field].label }}</dt>
		<dd>{{ form[field]() }}</dd>
		{% if form[field].errors %}
		{% for e in form[field].errors %}
		<p class="help-block">{{ e }}</p>
		{% endfor %}
		{% endif %}
		{% endfor %}
	</dl>
	<p>
		<input type=submit value="Publish" class="btn btn-dark">
		<br>
		<h7 style="color: red;"> {{ error }}</h7>
</form>
{% endblock %}

monolith/templates/mailbox.html
{% extends "base.html" %}
{% block title %}Mailbox{% endblock %}

{% block html_head %}
<style>
	/* The Modal (background) */
	.modal {
		display: none;
		/* Hidden by default */
		position: fixed;
		/* Stay in place */
		z-index: 1;
		/* Sit on top */
		left: 0;
		top: 0;
		width: 100%;
		/* Full width */
		height: 100%;
		/* Full height */
		overflow: auto;
		/* Enable scroll if needed */
		background-color: rgb(0, 0, 0);
		/* Fallback color */
		background-color: rgba(0, 0, 0, 0.4);
		/* Black w/ opacity */
	}

	/* Modal Content/Box */
	.modal-content {
		background-color: #fefefe;
		text-align: left;
		margin: 15% auto;
		/* 15% from the top and centered */
		padding: 20px;
		border: 1px solid #888;
		width: 80%;
		/* Could be more or less, depending on screen size */
	}

	/* The Close Button */
	.close {
		color: #aaa;
		text-align: right;
		float: right;
		font-size: 28px;
		font-weight: bold;
	}

	.close:hover,
	.close:focus {
		color: black;
		text-decoration: none;
		cursor: pointer;
	}
</style>
{% endblock %}

{% block content %}
{{ ckeditor.load() }}

<h1>Mailbox</h1><br>
<a href="/" class="btn btn-outline-primary">Homepage</a><br><br>

<h3>Received messages</h3>
<br>
<table class="table table-light" id="received"></table>
<br>

<h3>Delivered messages</h3>
<table class="table table-light" id="sent"></table>

<!--MODAL FOR READ MESSAGE-->
<div id="modal_read" class="modal">
	<div class="modal-content">
		<span class="close">&times;</span>
		<div id="modal_read_text">
			<p>ASE &lt;3 </p>
		</div>
	</div>
</div>

<!--MODAL FOR REPLY MESSAGE-->
<div id="modal_reply" class="modal">
	<div class="modal-content">
		<span class="close">&times;</span>
		<h2>Reply to message</h2>
		<form method="POST" id="reply-form" enctype="multipart/form-data">
			<input type="hidden" id="draft_id" name="draft_id" value=''>
			<label for="recipient">Recipient</label><br>
			<select name="recipient">
				<option id="recipient_reply" value="${msg.sender_id}" selected>${msg.email}</option>
			</select><br><br>
			<label for="text">Message text</label><br>
			{{ ckeditor.config(name='reply_text') }}
			{{ ckeditor.create(name='reply_text') }}<br><br>
			<label for="attachment">Attach an image</label><br>
			<input id="attachment" name="attachment" type="file"><br><br>
			<label for="delivery_date">Choose a time for delivering message</label><br>
			<input type="datetime-local" id="delivery_date" name="delivery_date" required /><br><br>
			<button type="button" onclick='javascript:send_msg_reply_forward("reply-form" )'
				class="btn btn-primary">Send message</button>
		</form>
	</div>
</div>

<!--MODAL FOR Forward-->
<div id="modal_forward" class="modal">
	<div class="modal-content">
		<span class="close">&times;</span>
		<h2>Forward message</h2>
		<form method="POST" id="forward-form-rec">
			<input type="hidden" name="draft_id" value=''>
			<label for="recipient">Recipient</label><br>
			<select id="recipient" name="recipient"></select><br><br>
			<label for="text">Message text</label><br>

			{{ ckeditor.config(name='fwd_text') }}
			{{ ckeditor.create(name='fwd_text') }}<br><br>
			<label for="delivery_date">Choose a time for delivering message</label><br>
			<input type="datetime-local" id="delivery_date" name="delivery_date" required /><br><br>
			<button type="button" onclick='javascript:send_msg_reply_forward("forward-form-rec" , true)'
				class="btn btn-primary">Send message</button>
		</form>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script>
	var MEDIA_URL = `{{ url_for('static', filename='user_uploads/MEDIA') }}`
</script>
<script src="{{ url_for('static', filename='mailbox.js') }}"></script>
<script>
	function refreshTables() {
		$.get("{{url_for('message._get_received_messages_metadata')}}", function (data) { buildTableReceived(data); });
		$.get("{{url_for('message._get_sent_messages_metadata')}}", function (data) { buildTableSent(data) });
	}

	refreshTables();
	setInterval(refreshTables, 10 * 1000);
</script>
{% endblock %}

monolith/templates/report_user.html
{% extends "base.html" %}
{% block title %}Report a user{% endblock %}

{% block content %}
<h1>Report a user</h1>

<a href="/" class="btn btn-outline-primary">Homepage</a>
<a href="{{url_for('home.settings')}}" class="btn btn-outline-primary">Back to settings</a><br><br>

<h4>Insert the email of the user you want to report</h4>

<form method="POST">
	<input type="text" id="useremail" name="useremail"><br><br>
	<button type="submit" class="btn btn-danger" formaction="{{url_for('users.report')}}">Report</button>
</form><br>

{% if error != "" %}
<p style="color:red;">{{error}}</p>
{% endif %}
{% if reported != "" %}
{{ reported }}
{% endif %}
{{feedback}}
{% endblock %}

monolith/templates/reset_password.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}

{% block content %}
<h1>Reset password</h1>
<a href="/" class="btn btn-outline-primary">Homepage</a>
<a href="{{url_for('home.settings')}}" class="btn btn-outline-primary">Back to settings</a><br><br>

<div>
	<form action="" method="POST">
		<h5>Current password</h5> {{ form.currentpassword }}
		<h5>New password</h5> {{ form.newpassword }}
		<h5>Confirm password</h5>{{ form.confirmpassword }}
		<p>
			<br>
			<input type=submit value="Submit" class="btn btn-outline-primary"><br>
			<h7 style="color: red;"> {{ error }}</h7>
			<h7 style="color: green;"> {{ success }}</h7>
</div>
{% endblock %}

monolith/templates/search_user.html
{% extends "base.html" %}
{% block title %}Search user{% endblock %}

{% block content %}
<h1>Search for a user</h1>
<a href="/" class="btn btn-outline-primary">Homepage</a><br><br>

<br><label>Search <input id="search" type="text" placeholder="Type to search"></label><br><br>
<table class="table table-light" id="users">
	<thead>
		<tr>
			<th scope="col">E-mail</th>
			<th scope="col">First name</th>
			<th scope="col">Last name</th>
		</tr>
	</thead>
</table>
{% endblock %}
{% block scripts %}
<script>
	$.get("{{url_for('users.get_users_list_json')}}", function (data) { buildTable(data); });

	function buildTable(data) {
		console.log(data);
		var table = document.getElementById('users');
		for (var i = 0; i < data.length; i++) {
			user = data[i];
			var row = `<tr>
					<td>${user.email}</td>
					<td>${user.firstname}</td>
					<td>${user.lastname}</td>
			  </tr>`;
			table.innerHTML += row;

		}
		search();
	}

	//Inspired by https://stackoverflow.com/a/9127872/12346032
	function search() {
		var $rows = $('#users tbody tr');
		$('#search').keyup(function () {

			var val = '^(?=.*\\b' + $.trim($(this).val()).split(/\s+/).join('\\b)(?=.*\\b') + ').*$',
				reg = RegExp(val, 'i'),
				text;

			$rows.show().filter(function () {
				text = $(this).text().replace(/\s+/g, ' ');
				return !reg.test(text);
			}).hide();
		});
	}
</script>
{% endblock %}

monolith/templates/users.html
<html>

<body>
	<h1>User List</h1>
	<ul>
		{% for user in users: %}
		<li>
			{{user.firstname}} {{user.lastname}}, {{user.email}}
		</li>
		{% endfor %}
	</ul><br>
	<a href="/">Home</a>
</body>

</html>